# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.7.5-node-browsers
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
          RAILS_MASTER_KEY: 888f0d8e873acaa9097b0e634e6debbf

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.24
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: insta_test
          POSTGRES_HOST_AUTH_METHOD: trust

      - image: circleci/redis:5.0.14

    working_directory: ~/repo


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo apt remove nodejs npm
      - run: sudo rm -rf /usr/local/bin/node*
      - run: sudo rm -rf /usr/local/bin/npm*
      - run: sudo rm -rf /etc/apt/sources.list.d/nodesource.list

      - run: curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
      - run: sudo apt list -a nodejs
      - run: sudo apt install nodejs npm
      - run:
          name: install dependencies
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: sudo apt-get --allow-releaseinfo-change update
      - run: sudo apt install -y postgresql-client 
      - run: sudo apt install -y ffmpeg
      #- run: curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && apt-get install -y nodejs

      - restore_cache:
          keys:
            - yarn-cache-v1-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-
      - run: yarn install --cache-folder ~/.cache/yarn
      - run: bundle exec rake webpacker:compile
      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:

            - ~/.cache/yarn
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - run:
          name: react tests
          command: |
            yarn run test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
